apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    app: flask-restapi-crud-app-deployment
type: Opaque
data:
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
