version: "3"

# define 2 services: flask_crud_app and postgres_db
services:
  flask-restapi-crud-app:
    container_name: flask-restapi-crud-app-container
    image: horlar/flask-restapi-crud-app:${IMAGE_TAG}
    restart: always
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5000:5000"
    depends_on:
      flask_db:
        condition: service_healthy


  flask_db:
    container_name: flask_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    # volumes:
    #   - pgdata:/var/lib/postgresql/data/pgdata
    
volumes:
  pgdata: 